# Sesión 29

En está sesión e explica el algortimo de Floyd-Warshall.


Este algortimo considera los vertices intermedios del camino más corto.
Dado un camino $p = \{v_1,v_2,...,v_l\}$, un vértice intermedio es cualquier vértice en el conjunto $\{v_2,...,v_{l-1}\}$

### Solución recursiva



Definimos:
 - $ d_{ij}^{(k)}$: la distancia mínima entre el nodo $ i $ y el nodo $ j $, considerando solo los nodos $ \{1, 2, \dots, k\} $ como intermediarios.


El algoritmo se basa en la siguiente relación de recurrencia:

$$
\mathrm{d}_{ij}^{(k)} = \begin{cases}
       w(i, j) & \text{si } k = 0, \\
       \min\left(d_{ij}^{(k-1)}, d_{ik}^{(k-1)} + d_{kj}^{(k-1)}\right) & \text{si } k \geq 1
\end{cases} 
$$

### Pseudocódigo
 ```
 Floyd-Warshall(W, n)
 1. D^(0) = W
 2. for k = 1 to n:
 3.     let D^(k) = (dij^(k)) be a new n x n matrix
 4.     for i = 1 to n:
 5.         for j = 1 to n:
 6.             d[i][j] = min(d[i][j], d[i][k] + d[k][j])
 7. return D^(n)
 
 ```


El tiempo de ejecución del algoritmo de Floyd- Warshall esta determinado por el número de vertices v del grafo, con tres ciclos anidados, su tiempo de complejidad es de $\theta(v^3)$

### Implementación

In [6]:
function floyd_warshall(W::Matrix{Float64})
    
    n = size(W, 1)  
    D = copy(W)     

    
    for k in 1:n
        println("\nIteración k = $k:")
        for i in 1:n
            for j in 1:n
                
                D[i, j] = min(D[i, j], D[i, k] + D[k, j])
            end
        end
        println("Matriz D^($k):")
        display(D)
    end

    return D 
end




floyd_warshall (generic function with 1 method)

In [7]:
#### Ejemplo 

W = [
    0.0   3.0   8.0   Inf  -4.0;
    Inf   0.0   Inf   1.0  7.0;
    Inf   4.0   0.0   Inf  Inf;
    2.0   Inf   -5.0  0.0  Inf;
    Inf   Inf   Inf   6.0  0.0
]

println("Matriz de adyacencia inicial:")
display(W)


distances = floyd_warshall(W)

println("\nMatriz de distancias más cortas:")
display(distances)

Matriz de adyacencia inicial:


5×5 Matrix{Float64}:
  0.0   3.0   8.0  Inf   -4.0
 Inf    0.0  Inf    1.0   7.0
 Inf    4.0   0.0  Inf   Inf
  2.0  Inf   -5.0   0.0  Inf
 Inf   Inf   Inf    6.0   0.0


Iteración k = 1:
Matriz D^(1):


5×5 Matrix{Float64}:
  0.0   3.0   8.0  Inf   -4.0
 Inf    0.0  Inf    1.0   7.0
 Inf    4.0   0.0  Inf   Inf
  2.0   5.0  -5.0   0.0  -2.0
 Inf   Inf   Inf    6.0   0.0


Iteración k = 2:
Matriz D^(2):


5×5 Matrix{Float64}:
  0.0   3.0   8.0  4.0  -4.0
 Inf    0.0  Inf   1.0   7.0
 Inf    4.0   0.0  5.0  11.0
  2.0   5.0  -5.0  0.0  -2.0
 Inf   Inf   Inf   6.0   0.0


Iteración k = 3:
Matriz D^(3):


5×5 Matrix{Float64}:
  0.0   3.0   8.0  4.0  -4.0
 Inf    0.0  Inf   1.0   7.0
 Inf    4.0   0.0  5.0  11.0
  2.0  -1.0  -5.0  0.0  -2.0
 Inf   Inf   Inf   6.0   0.0


Iteración k = 4:
Matriz D^(4):


5×5 Matrix{Float64}:
 0.0   3.0  -1.0  4.0  -4.0
 3.0   0.0  -4.0  1.0  -1.0
 7.0   4.0   0.0  5.0   3.0
 2.0  -1.0  -5.0  0.0  -2.0
 8.0   5.0   1.0  6.0   0.0


Iteración k = 5:
Matriz D^(5):


5×5 Matrix{Float64}:
 0.0   1.0  -3.0  2.0  -4.0
 3.0   0.0  -4.0  1.0  -1.0
 7.0   4.0   0.0  5.0   3.0
 2.0  -1.0  -5.0  0.0  -2.0
 8.0   5.0   1.0  6.0   0.0


Matriz de distancias más cortas:


5×5 Matrix{Float64}:
 0.0   1.0  -3.0  2.0  -4.0
 3.0   0.0  -4.0  1.0  -1.0
 7.0   4.0   0.0  5.0   3.0
 2.0  -1.0  -5.0  0.0  -2.0
 8.0   5.0   1.0  6.0   0.0

### Implementación de Floyd_Warshall con la matriz de predecesores

In [9]:
function floyd_warshall_with_predecessors(W::Matrix{Float64})

    n = size(W, 1)  
    D = copy(W)    
    Pi = zeros(Int, n, n)  

    for i in 1:n
        for j in 1:n
            if i != j && W[i, j] != Inf
                Pi[i, j] = i 
            end
        end
    end

    println("Matriz inicial D^(0) y Pi:")
    display(D)
    display(Pi)

    
    for k in 1:n
        println("\nIteración k = $k:")
        for i in 1:n
            for j in 1:n
                
                if D[i, j] > D[i, k] + D[k, j]
                    D[i, j] = D[i, k] + D[k, j]  
                    Pi[i, j] = Pi[k, j] 
                end
            end
        end

        
        println("Matriz D^($k):")
        display(D)
        println("Matriz Pi^($k):")
        display(Pi)
    end

    return D, Pi 
end



floyd_warshall_with_predecessors (generic function with 1 method)

In [8]:

# Creamos la matriz de adyacencia inicial
W = [
    0.0   3.0   8.0   Inf  -4.0;
    Inf   0.0   Inf   1.0  7.0;
    Inf   4.0   0.0   Inf  Inf;
    2.0   Inf   -5.0  0.0  Inf;
    Inf   Inf   Inf   6.0  0.0
]

println("Matriz de adyacencia inicial:")
display(W)


distances, predecessors = floyd_warshall_with_predecessors(W)

println("\nMatriz de distancias más cortas:")
display(distances)

println("\nMatriz final de predecesores:")
display(predecessors)


Matriz de adyacencia inicial:


5×5 Matrix{Float64}:
  0.0   3.0   8.0  Inf   -4.0
 Inf    0.0  Inf    1.0   7.0
 Inf    4.0   0.0  Inf   Inf
  2.0  Inf   -5.0   0.0  Inf
 Inf   Inf   Inf    6.0   0.0

Matriz inicial D^(0) y Pi:


5×5 Matrix{Float64}:
  0.0   3.0   8.0  Inf   -4.0
 Inf    0.0  Inf    1.0   7.0
 Inf    4.0   0.0  Inf   Inf
  2.0  Inf   -5.0   0.0  Inf
 Inf   Inf   Inf    6.0   0.0

5×5 Matrix{Int64}:
 0  1  1  0  1
 0  0  0  2  2
 0  3  0  0  0
 4  0  4  0  0
 0  0  0  5  0


Iteración k = 1:
Matriz D^(1):


5×5 Matrix{Float64}:
  0.0   3.0   8.0  Inf   -4.0
 Inf    0.0  Inf    1.0   7.0
 Inf    4.0   0.0  Inf   Inf
  2.0   5.0  -5.0   0.0  -2.0
 Inf   Inf   Inf    6.0   0.0

Matriz Pi^(1):


5×5 Matrix{Int64}:
 0  1  1  0  1
 0  0  0  2  2
 0  3  0  0  0
 4  1  4  0  1
 0  0  0  5  0


Iteración k = 2:
Matriz D^(2):


5×5 Matrix{Float64}:
  0.0   3.0   8.0  4.0  -4.0
 Inf    0.0  Inf   1.0   7.0
 Inf    4.0   0.0  5.0  11.0
  2.0   5.0  -5.0  0.0  -2.0
 Inf   Inf   Inf   6.0   0.0

Matriz Pi^(2):


5×5 Matrix{Int64}:
 0  1  1  2  1
 0  0  0  2  2
 0  3  0  2  2
 4  1  4  0  1
 0  0  0  5  0


Iteración k = 3:
Matriz D^(3):


5×5 Matrix{Float64}:
  0.0   3.0   8.0  4.0  -4.0
 Inf    0.0  Inf   1.0   7.0
 Inf    4.0   0.0  5.0  11.0
  2.0  -1.0  -5.0  0.0  -2.0
 Inf   Inf   Inf   6.0   0.0

Matriz Pi^(3):


5×5 Matrix{Int64}:
 0  1  1  2  1
 0  0  0  2  2
 0  3  0  2  2
 4  3  4  0  1
 0  0  0  5  0


Iteración k = 4:
Matriz D^(4):


5×5 Matrix{Float64}:
 0.0   3.0  -1.0  4.0  -4.0
 3.0   0.0  -4.0  1.0  -1.0
 7.0   4.0   0.0  5.0   3.0
 2.0  -1.0  -5.0  0.0  -2.0
 8.0   5.0   1.0  6.0   0.0

Matriz Pi^(4):


5×5 Matrix{Int64}:
 0  1  4  2  1
 4  0  4  2  1
 4  3  0  2  1
 4  3  4  0  1
 4  3  4  5  0


Iteración k = 5:
Matriz D^(5):


5×5 Matrix{Float64}:
 0.0   1.0  -3.0  2.0  -4.0
 3.0   0.0  -4.0  1.0  -1.0
 7.0   4.0   0.0  5.0   3.0
 2.0  -1.0  -5.0  0.0  -2.0
 8.0   5.0   1.0  6.0   0.0

Matriz Pi^(5):


5×5 Matrix{Int64}:
 0  3  4  5  1
 4  0  4  2  1
 4  3  0  2  1
 4  3  4  0  1
 4  3  4  5  0


Matriz de distancias más cortas:


5×5 Matrix{Float64}:
 0.0   1.0  -3.0  2.0  -4.0
 3.0   0.0  -4.0  1.0  -1.0
 7.0   4.0   0.0  5.0   3.0
 2.0  -1.0  -5.0  0.0  -2.0
 8.0   5.0   1.0  6.0   0.0


Matriz final de predecesores:


5×5 Matrix{Int64}:
 0  3  4  5  1
 4  0  4  2  1
 4  3  0  2  1
 4  3  4  0  1
 4  3  4  5  0